security:
  always_authenticate_before_granting: true
  encoders:
    App\Domain\User\User:
      algorithm: bcrypt

  providers:
    from_database:
      entity:
        class: App\Domain\User\User
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      logout:
        path: /logout
        target: /login
      guard:
        authenticators:
          - App\Domain\User\Authenticator

  access_control:
