vich_uploader:
    db_driver: orm

    mappings:
        products_img:
            uri_prefix: /images/recipe
            upload_destination: '%kernel.project_dir%/public/images/recipe'
            namer: Vich\UploaderBundle\Naming\UniqidNamer